[package]
name = "inputui"
version = "0.1.0"
edition = "2021"

[dependencies]
inputbot = "0.6.0"
ratatui = { version = "0.27.0", features = ["unstable-widget-ref"] }

[profile.release]
strip = true
lto = true
